import type { Metadata } from "next";
import "./index.scss";
import Main from "./Main";
import BodyClickCircle from "@/UI/BodyClickCircle";
import UITheme from "@/UI/material";
import TopLoadingBar from "./TopLoadingBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="__nextJs">
          <BodyClickCircle>
            <UITheme
              themeProviderProps={{
                modeStorageKey: "portfolio-theme",
                colorSchemeStorageKey: "portfolio-color-theme",
              }}
            >
              <TopLoadingBar>
                <Main>{children}</Main>
              </TopLoadingBar>
            </UITheme>
          </BodyClickCircle>
        </div>
      </body>
    </html>
  );
}
